language: node_js
node_js:
  - 4
  - 5
  - 6
 
services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -uroot test < rsc/mysql-setup.sql
  - mv settings.travis.json settings.json